# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"

python:
  # only numpy is in the requirements file; the rest is mocked by autodoc_mock_imports
  install:
    - requirements: docs/requirements.txt
    - method: setuptools
      path: .  # setup.py includes a hack that emulates --no-deps for RTD
