# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.13"

python:
  # only numpy and sphinx theme in requirements; heavy deps are mocked by autodoc_mock_imports
  # We don't install the package itself to avoid dependency issues on RTD
  install:
    - requirements: docs/requirements.txt
